name: 'ECR Login'
description: 'ECR Login'
runs:
  using: "composite"
  steps:
    - name: ECR Login
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        sudo apt-get update
        sudo apt-get install -y less
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        OUTPUT="$(aws ecr get-login-password --region us-west-2)"
        echo "::set-output name=ecr_pass::${OUTPUT}"