name: 'ECR Login'
description: 'ECR Login'
inputs:
  awsRegion:
    description: 'AWS Region'
    required: true
    default: 'us-west-2'
outputs:
  ecr_pass:
    description: "ECR Pass"
    value: ${{ steps.ecr_pass.outputs.ecr_pass }}
runs:
  using: "composite"
  steps:
    - name: ECR Login
      id: ecr_pass
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        sudo apt-get update
        sudo apt-get install -y less
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qq awscliv2.zip
        sudo ./aws/install
        aws --version
        OUTPUT="$(aws ecr get-login-password --region ${{ inputs.awsRegion }})"
        echo "::set-output name=ecr_pass::${OUTPUT}"
